version: "3.1"

services:
  notebook-server:
    build:
      context: .
      args:
        DS_DIR: ds_stack
    ports:
      - "8888:8888"
    volumes:
      - .:/ds_stack
    tty: true
    stdin_open: true
    environment:
      REDSHIFT_PASSWORD_FILE: /run/secrets/redshift_password
    secrets:
      - redshift_password

secrets:
  redshift_password:
    file: ~/.credentials/redshift_goodrx
